name: 'Terraform Actions'
description: 'Run Terraform commands'
inputs:
  gcp_sa_key:
    description: 'GCP Service Account Key'
    required: false
    default: ${{ github.event.inputs.GCP_SA_KEY }}
  working_directory:
    description: 'Terraform working directory'
    required: false
    default: 'terraform/environments/dev'
  command:
    description: 'Terraform command to run'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup GCP Credentials
      if: inputs.gcp_sa_key != ''
      run: |
        echo "$GCP_SA_KEY" > gcp-credentials.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=${PWD}/gcp-credentials.json" >> $GITHUB_ENV
      env:
        GCP_SA_KEY: ${{ inputs.gcp_sa_key }}
      shell: bash

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Run Terraform Command
      run: terraform -chdir=${{ inputs.working_directory }} ${{ inputs.command }}
      shell: bash
