name: 'Setup Terraform and Google Cloud'
description: 'Setup Terraform and Google Cloud for GCP operations'
inputs:
  terraform_version:
    description: 'Terraform version'
    required: true
    default: '1.3.0'
  gcp_sa_key:
    description: 'GCP Service Account Key'
    required: true
  project_id:
    description: 'GCP Project ID'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Setup Google Cloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ inputs.gcp_sa_key }}
        project_id: ${{ inputs.project_id }}
        export_default_credentials: true
