name: Deploy to GCP with Terraform

on:
  push:
    paths:
      - 'terraform/environments/dev/main.tf'
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/terraform_actions.yml 
    #uses: eechukwu/devops-pro-gcp-terraform/.github/workflows/terraform_actions.yml@main
    with:
      #terraform_command: 'init plan validate apply -auto-approve'
      terraform_command: 'init -reconfigure && terraform validate && terraform plan && terraform apply -auto-approve'
    secrets: inherit
