name: Terraform Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-gcloud:
    name: Setup Google Cloud
    runs-on: ubuntu-latest
    outputs:
      gcp_project: ${{ steps.set_env.outputs.gcp_project }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Google Cloud
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: gcp-devops-pro-405617
    - name: Set GCP Project ID Env
      id: set_env
      run: echo "::set-output name=gcp_project::$(gcloud config get-value project)"

  terraform-init:
    name: Terraform Initialize
    needs: setup-gcloud
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - run: terraform init
      working-directory: ./terraform/environments/dev
      env:
        GOOGLE_PROJECT: ${{ needs.setup-gcloud.outputs.gcp_project }}

  terraform-fmt:
    name: Terraform Format Check
    needs: terraform-init
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: terraform fmt -check
      working-directory: ./terraform/environments/dev

  terraform-plan:
    name: Terraform Plan
    needs: terraform-fmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: terraform plan
      working-directory: ./terraform/environments/dev

  terraform-apply:
    name: Terraform Apply
    if: github.ref == 'refs/heads/main'
    needs: terraform-plan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: terraform apply -auto-approve
      working-directory: ./terraform/environments/dev
