name: Deploy Infra Via Terraform

on:
  workflow_dispatch:
    inputs:
      modules:
        description: 'Modules to deploy (e.g., "network", "compute_instance", or "all")'
        required: true
        default: 'all'

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud
        run: |
          echo "$GCP_SA_KEY" > gcp-sa-key.json
          gcloud auth activate-service-account --key-file=gcp-sa-key.json
          rm gcp-sa-key.json
          gcloud config set project gcp-devops-pro-405617
          gcloud config set compute/region europe-west2
          gcloud config set compute/zone europe-west2-a
          gcloud auth configure-docker
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.1.0'

      - name: Terraform Init
        run: terraform -chdir=./terraform/environments/dev init -backend=false -get-plugins=false -input=false -lock=false -force-copy -no-color -reconfigure -var module_variable_optional_attrs=true

      - name: Terraform Validate
        run: terraform -chdir=./terraform/environments/dev validate

      - name: Terraform Plan
        run: |
          if [ "${{ github.event.inputs.modules }}" == "all" ]; then
            terraform -chdir=./terraform/environments/dev plan
          else
            IFS=',' read -ra MODULES <<< "${{ github.event.inputs.modules }}"
            for module in "${MODULES[@]}"; do
              terraform -chdir=./terraform/environments/dev plan -target=module.$module
            done
          fi

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
        run: |
          if [ "${{ github.event.inputs.modules }}" == "all" ]; then
            terraform -chdir=./terraform/environments/dev apply -auto-approve
          else
            IFS=',' read -ra MODULES <<< "${{ github.event.inputs.modules }}"
            for module in "${MODULES[@]}"; do
              terraform -chdir=./terraform/environments/dev apply -auto-approve -target=module.$module
            done
          fi
