name: Test GCP Service Account Key

on: 
  workflow_dispatch:

jobs:
  test-gcp-auth:
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Set GCP project ID
      - name: Set GCP Project ID
        run: gcloud config set project gcp-devops-pro-405617

      # List GCP projects for testing authentication
      - name: List GCP Projects
        run: gcloud projects list
