name: Test GCP Service Account Key

on: 
  workflow_dispatch:

jobs:
  test-gcp-auth:
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Setup Google Cloud SDK
      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: gcp-devops-pro-405617
          export_default_credentials: true

      # Authenticate and list GCP projects (for testing)
      - name: List GCP Projects
        run: gcloud projects list
