name: Terraform Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 1: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.1.0'

      # Step 2: Set up Google Cloud environment for Terraform to interact with GCP.
      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}  # Use a secret for GCP authentication.
          project_id: gcp-devops-pro-405617
          export_default_credentials: true

      # Step 3: Export Google Cloud credentials to a file
      - name: Export Google Cloud Credentials
        run: echo "$GCP_SA_KEY" > keyfile.json
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

      # Step 4: Set GOOGLE_APPLICATION_CREDENTIALS environment variable
      - name: Set Google Cloud Credentials Environment Variable
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/keyfile.json" >> $GITHUB_ENV

      # Step 5: Initialize Terraform (specifying the dev environment path)
      - name: Terraform Init
        run: terraform -chdir=./terraform/environments/dev init -reconfigure -upgrade

      # Step 6: Validate Terraform configuration
      - name: Terraform Validate
        run: terraform -chdir=./terraform/environments/dev validate

      # Step 7: Plan Terraform changes
      - name: Terraform Plan
        run: terraform -chdir=./terraform/environments/dev plan

      # Step 7: Plan Terraform changes
      - name: Terraform Apply
        run: terraform -chdir=./terraform/environments/dev apply -auto-approve 
