name: Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      modules:
        description: 'Modules to deploy (e.g., network, compute_instance)'
        required: true
        default: 'all'

jobs:
  terraform:
    name: Terraform CI/CD
    runs-on: ubuntu-latest
    env:
      TF_ROOT: './terraform/environments/dev'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Echo Workflow Inputs
        run: |
          echo "Modules to deploy: ${{ github.event.inputs.modules }}"

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: gcp-devops-pro-405617
          export_default_credentials: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.1.0'

      - name: Terraform Init
        run: terraform init -input=false -backend=true
        working-directory: ${{ env.TF_ROOT }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ env.TF_ROOT }}

      - name: Determine Target Modules
        id: target_modules
        run: |
          TARGETS=""
          IFS=',' read -ra MODULES <<< "${{ github.event.inputs.modules }}"
          for module in "${MODULES[@]}"; do
            if [ "$module" != "all" ]; then
              TARGETS="$TARGETS -target=module.$module"
            fi
          done
          echo "Determined targets: $TARGETS"
          echo "TARGETS=$TARGETS" >> $GITHUB_ENV

      - name: Terraform Plan
        run: |
          echo "Running Terraform Plan with targets: $TARGETS"
          terraform plan $TARGETS
        working-directory: ${{ env.TF_ROOT }}
        if: env.TARGETS != '' || github.event.inputs.modules == 'all'

      - name: Terraform Apply
        run: |
          echo "Running Terraform Apply with targets: $TARGETS"
          terraform apply $TARGETS -auto-approve
        working-directory: ${{ env.TF_ROOT }}
        if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch' && (env.TARGETS != '' || github.event.inputs.modules == 'all')
