name: Terraform Workflow

on:
  push:
    branches:
      - main

env:
  TF_ROOT: './terraform/environments/dev'  # Set the Terraform root directory as an environment variable.

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Google Cloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: gcp-devops-pro-405617
        export_default_credentials: true

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: latest

    - name: Terraform Init
      run: terraform -chdir=$TF_ROOT init 
    - name: Terraform Validate
      run: terraform -chdir=$TF_ROOT validate

    - name: Terraform Plan
      run: terraform -chdir=$TF_ROOT plan

    - name: Terraform Apply
      run: terraform -chdir=$TF_ROOT apply -auto-approve
