name: Deploy GCP Resources

on:
  workflow_dispatch:
  push:
    paths:
      - 'path/to/your/folder/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Terraform and Google Cloud
        uses: devops-pro-gcp-terraform/.github/actions/setup-terraform-gcloud@main
        with:
          terraform_version: '1.3.0'
          gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
          project_id: gcp-devops-pro-405617

      - name: Terraform Init
        run: terraform -chdir=./terraform/environments/dev init -reconfigure -upgrade

      - name: Terraform Validate
        run: terraform -chdir=./terraform/environments/dev validate

      - name: Terraform Plan
        run: terraform -chdir=./terraform/environments/dev plan

      - name: Terraform Apply
        run: terraform -chdir=./terraform/environments/dev apply -auto-approve
