name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform CI/CD
    runs-on: ubuntu-latest

    strategy:
      matrix:
        resource: ["network", "compute_instance"]  # Update with actual resource names

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: gcp-devops-pro-405617
          export_default_credentials: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.1.0'

      - name: Cache Terraform Plugins
        uses: actions/cache@v2
        with:
          path: |
            ./.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Terraform Init
        run: |
          mkdir -p ./.terraform.d/plugin-cache
          terraform init -input=false -backend=true -plugin-dir=./.terraform.d/plugin-cache
        working-directory: ./terraform/environments/dev

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform/environments/dev

      - name: Terraform Plan for Specific Resource
        run: terraform plan -target=module.${{ matrix.resource }}
        working-directory: ./terraform/environments/dev

      - name: Terraform Apply for Specific Resource
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -target=module.${{ matrix.resource }} -auto-approve
        working-directory: ./terraform/environments/dev
