name: Deploy to GCP with Terraform

on:
  push:
    paths:
      - 'terraform/environments/dev/main.tf'
  workflow_dispatch:

jobs:
  deploy:
    uses: terraform_actions.yml
    with:
      terraform_command: 'apply -auto-approve'
