name: Terraform Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-gcloud:
    name: Setup Google Cloud
    runs-on: ubuntu-latest
    outputs:
      gcp_project: ${{ steps.set_env.outputs.gcp_project }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Google Cloud
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: gcp-devops-pro-405617
    - name: Set GCP Project ID Env
      id: set_env
      run: echo "::set-output name=gcp_project::$(gcloud config get-value project)"

  terraform-init:
    name: Terraform Initialize
    needs: setup-gcloud
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Terraform Initialize
      run: terraform init
      working-directory: ./terraform/environments/dev
    - name: Terraform Initialize Modules
      run: terraform init
      working-directory: ./terraform/modules/compute_instance

  terraform-fmt:
    name: Terraform Format and Commit
    needs: terraform-init
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Terraform Format
      run: |
        terraform fmt
        git diff --exit-code || (git add . && git config --global user.name 'Your Name' && git config --global user.email 'your-email@example.com' && git commit -m "Automated Terraform fmt" && git push)
      working-directory: ./terraform/environments/dev

  terraform-plan:
    name: Terraform Plan
    needs: terraform-fmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Terraform Plan
      run: terraform plan
      working-directory: ./terraform/environments/dev

  terraform-apply:
    name: Terraform Apply
    if: github.ref == 'refs/heads/main'
    needs: terraform-plan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./terraform/environments/dev
