name: Deploy Infra Via Terraform

on:
  workflow_dispatch:
    inputs:
      modules:
        description: 'Modules to deploy (e.g., "network", "compute_instance", or "all")'
        required: true
        default: 'all'  # Default input when none is provided.

jobs:
  terraform-deploy:
    name: Terraform CI/CD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Google Cloud SDK
        run: |
          curl -sSL https://sdk.cloud.google.com | bash
          exec -l $SHELL
          gcloud --version
        env:
          PATH: ${{ runner.toolsDirectory }}/google-cloud-sdk/bin:${{ PATH }}

      - name: Authenticate with Google Cloud
        run: gcloud auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY }}

      - name: Set Up Terraform
        run: |
          terraform_version='1.1.0'
          terraform_url="https://releases.hashicorp.com/terraform/${terraform_version}/terraform_${terraform_version}_linux_amd64.zip"
          curl -o terraform.zip ${terraform_url}
          unzip terraform.zip
          mv terraform ${{ runner.toolsDirectory }}/terraform
          terraform --version
        env:
          PATH: ${{ runner.toolsDirectory }}:${{ PATH }}

      - name: Terraform Init
        run: terraform init -input=false -backend=true
        working-directory: ${{ env.TF_ROOT }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ env.TF_ROOT }}

      - name: Terraform Plan
        run: |
          if [ "${{ github.event.inputs.modules }}" == "all" ]; then
            terraform plan
          else
            IFS=',' read -ra MODULES <<< "${{ github.event.inputs.modules }}"
            for module in "${MODULES[@]}"; do
              terraform plan -target=module.${module}
            done
          fi
        working-directory: ${{ env.TF_ROOT }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
        run: |
          if [ "${{ github.event.inputs.modules }}" == "all" ]; then
            terraform apply -auto-approve
          else
            IFS=',' read -ra MODULES <<< "${{ github.event.inputs.modules }}"
            for module in "${MODULES[@]}"; do
              terraform apply -auto-approve -target=module.${module}
            done
          fi
        working-directory: ${{ env.TF_ROOT }}
