name: Deploy to GCP with Terraform

on:
  push:
    paths:
      - 'terraform/environments/dev/main.tf'
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/terraform_actions.yml 
    with:
      terraform_command: 'init -reconfigure && validate && plan'
    secrets: inherit


