name: Terraform Destroy  # Name of the GitHub Actions workflow

on:
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  terraform-destroy:
    name: Destroy Terraform Infrastructure  # Name of the job
    runs-on: ubuntu-latest  # Specifies the operating system for the job

    steps:
      - name: Checkout Repository  # Step to check out the repository
        uses: actions/checkout@v2

      - name: Setup Google Cloud  # Step to set up Google Cloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}  # Specifies the service account key
          project_id: gcp-devops-pro-405617  # Specifies the project ID
          export_default_credentials: true  # Exports default credentials

      - name: Setup Terraform  # Step to set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.1.0'  # Specifies the Terraform version

      - name: Terraform Init  # Step to initialize Terraform
        run: terraform init
        working-directory: ./terraform/environments/dev  # Specifies the working directory for the command

      - name: Terraform Destroy  # Step to destroy Terraform infrastructure
        run: terraform destroy -auto-approve
        working-directory: ./terraform/environments/dev  # Specifies the working directory for the command
