name: Destroy Infra With Terraform

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Terraform and Google Cloud
        uses: ./.github/actions/setup-terraform-gcloud
        with:
          terraform_version: '1.3.0'
          gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
          project_id: gcp-devops-pro-405617

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/environments/dev

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./terraform/environments/dev
