name: Destroy Specific Terraform Module

on:
  workflow_dispatch:
    inputs:
      module_name:
        description: 'Name of the Terraform module to destroy (e.g., test-vpc-module)'
        required: false

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Terraform
        uses: ./.github/actions/terraform
        with:
          gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
          working_directory: 'terraform/environments/dev'
          command: 'destroy'
          module_name: ${{ github.event.inputs.module_name }}

