name: Terraform Destroy

on:
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  terraform-destroy:
    name: Destroy Terraform Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: gcp-devops-pro-405617
          export_default_credentials: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.1.0'

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/environments/dev

      - name: Terraform Refresh
        run: terraform refresh
        working-directory: ./terraform/environments/dev

      - name: Terraform Destroy
        run: |
          export TF_LOG=DEBUG
          terraform destroy -auto-approve
        working-directory: ./terraform/environments/dev
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
