name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      gcp_credentials:
        description: 'GCP Service Account Key (JSON format)'
        required: true

jobs:
  terraform-destroy:
    name: Destroy Terraform Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ github.event.inputs.gcp_credentials }}
          project_id: gcp-devops-pro-405617
          export_default_credentials: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.1.0'

      - name: Create Credentials File
        run: echo '${{ github.event.inputs.gcp_credentials }}' > gcp_credentials.json
        working-directory: ./terraform/environments/dev

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/environments/dev
        env:
          TF_VAR_gcp_credentials: ${{ github.event.inputs.gcp_credentials }}

      - name: Terraform Refresh
        run: terraform refresh
        working-directory: ./terraform/environments/dev
        env:
          TF_VAR_gcp_credentials: ${{ github.event.inputs.gcp_credentials }}

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./terraform/environments/dev
        env:
          TF_VAR_gcp_credentials: ${{ github.event.inputs.gcp_credentials }}
