name: Terraform Force Unlock

on:
  workflow_dispatch:
    inputs:
      unlock_code:
        description: 'Unlock Code'
        required: true

jobs:
  terraform-force-unlock:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Terraform and Google Cloud
        uses: ./.github/actions/setup-terraform-gcloud
        with:
          terraform_version: '1.1.0'  # Adjust version as necessary
          gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
          project_id: gcp-devops-pro-405617

      - name: Terraform Init
        run: terraform init -input=false -backend=true -reconfigure -upgrade
        working-directory: ./terraform/environments/dev

      - name: Terraform Force Unlock
        run: terraform force-unlock -force ${{ github.event.inputs.unlock_code }}
        working-directory: ./terraform/environments/dev
