name: Unlock Terraform State

on:
  workflow_dispatch:
    inputs:
      unlock_id:
        description: 'Terraform state lock ID'
        required: true

jobs:
  unlock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Terraform Unlock
        uses: ./.github/actions/terraform
        with:
          gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
          working_directory: 'terraform/environments/dev'
          command: 'unlock'
          unlock_id: ${{ github.event.inputs.unlock_id }}
